# Generated by Django 5.2.4 on 2025-07-24 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="test_cases",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="test_solutions",
        ),
        migrations.AddField(
            model_name="problem",
            name="constraints",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="creator",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="examples",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="hints",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="memory_limit",
            field=models.IntegerField(blank=True, default=256),
        ),
        migrations.AddField(
            model_name="problem",
            name="submissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="time_limit",
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
