# Generated by Django 5.2.4 on 2025-08-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0002_remove_problem_test_cases_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="examples",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="hints",
        ),
    ]
